import {
  Dashboard,
  UserList,
  AddUser,
  Tenement,
  Room,
  Car,
  Repair,
  Contract,
  Bill,
  Merchants,
  Surrender,
  Comments,
  All,
  Article,
  Equipment,
  Enengy,
  Settings,
  Personal,
} from './componentRoute';
export const componentMap = {
  '/dashboard': <Dashboard />,
  '/users/list': <UserList />,
  '/users/add': <AddUser />,
  '/estate/tenement': <Tenement />,
  '/estate/room': <Room />,
  '/estate/car': <Car />,
  '/repair': <Repair />,
  '/finance/contract': <Contract />,
  '/finance/surrender': <Surrender />,
  '/finance/bill': <Bill />,
  '/merchants': <Merchants />,
  '/operation/all': <All />,
  '/operation/article': <Article />,
  '/operation/comments': <Comments />,
  '/equipment': <Equipment />,
  '/energy': <Enengy />,
  '/settings': <Settings />,
  '/personal': <Personal />,
};
